### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by c933103** [trafficguide/alt-routes#20]
1. 過海巴士地圖影像檔，108漏咗銅鑼灣，110北角應該是雙向
2. 柴灣去沙田搜尋結果大部分沒有顯示轉車區域

**Comment by trafficguide** [comment]
Re 1:

呢個我錯；雖然啲圖唔係我整嘅，但係就唔記得咗講返個出處 (btw三幅圖都係來自連登)。好快補返。

更新：已經喺 #21 處理咗。

Re 2:

呢個我陣間去check check。應該係貪快開waypoint擴展網絡而冇打waypoint係乜名。

**Comment by trafficguide** [comment]
Re 2:

呢個要你自己做返個"reload from source"，電腦嘅就`ctrl + f5`，手機Chrome嘅就`由上面拉落嚟`。

其實應該係因為快存cache咗舊嘅script，load都會load返舊果個，之後update返個script之後，有啲人會睇唔到新果個script，變咗好似個script有問題。

基本上已回應樓主問題，冇乜嘢嘅話我close咗呢個先。
