### ISSUE TITLE
車程系數問題

### ISSUE THREAD

**Issue by c933103** [trafficguide/alt-routes#23]
點解觀塘去柴灣，601/619轉694轉82個車程系數會短過就咁601/619轉694？694同82基本上同路，速度亦都相約，點解轉多次車可以降低車程系數？

**Comment by trafficguide** [comment]
你好！

依家車程系數係兩個部分加埋一齊，一個係乘車距離，一個係候車時間。個「候車時間」係根據班次得出。

呢度係我錯，當初計乘車系數果陣，係將「候車時間」得分嘅0 set咗喺班次20分鐘嘅水平，即係班次夠快嘅話，個候車時間果part會出負數。呢個導致咗「轉多次車仲快」嘅錯誤訊息。

(其實我set zero果陣係諗緊沙田入天水圍，269D去到大欖轉其他車，可能比一程車仲快(元朗塞車論)，當中應該同班次有啲關係。)

之後會改返做由0分鐘班次計起，班次愈疏，「候車時間」得分愈高。

感謝提點！

**Comment by trafficguide** [comment]
已經喺 #24 搞掂呢個問題！

冇問題嘅話，我close咗呢個先。
